# Generated by Django 4.2a1 on 2023-01-22 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('startTime', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('endTime', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('site', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
