# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='duration',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='startTime',
            field=models.BigIntegerField(default=0),
        ),
    ]
