# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 19:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170919_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='duration',
        ),
        migrations.AddField(
            model_name='contest',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='contest',
            name='site',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
