# Generated by Django 2.1.7 on 2019-03-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171014_2337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
