# Generated by Django 2.1.7 on 2019-03-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
